#if defined _isamp_inventory_included
	#endinput
#endif
#define _isamp_inventory_included

#define INV_MAX_SLOTS           2
#define ITEM_NONE               -1
#define ITEM_WEAPON             1
#define ITEM_OTHER              2
#define ITEM_STORABLE           3

new itemName[][64] = {
	"NULO",
	"manopla",
	"palo de golf",
	"macana",
	"navaja",
	"bate",
	"pala",
	"palo de pool",
	"katana",
	"motosierra",
	"consolador doble punta",
	"consolador",
	"vibrador",
	"vibrador plateado",
	"flores",
	"baston",
	"granada",
	"granada de gas",
	"molotov",
	"NULO",
	"NULO",
	"NULO",
	"9mm",
	"9mm con silenciador",
	"DEagle",
	"escopeta",
	"escopeta recortada",
	"escopeta de combate",
	"uzi",
	"MP-5",
	"AK-47",
	"M4",
	"TEC-9",
	"rifle de caza",
	"rifle francotirador",
	"RPG-7",
	"lanzamisiles",
	"lanzallamas",
	"minigun",
	"carga explosiva",
	"detonador",
	"aerosol",
	"extinguidor",
	"camara de fotos",
	"vision nocturna",
	"vision termica",
	"paracaidas",
	"caja de materiales",
	"bidón de combustible", // 48
	"materia prima",
	"productos",
	"dinero",
	"sandwich",
	"alfajor",
	"botella de agua"
};

